### ISSUE TITLE
Provide tagged releases

### ISSUE THREAD

**Issue by fago** [relaxedws/couchdb-replicator#11]
Please provide tagged releases. 

Tagged releases help quite a bit to be able to require stable releases and semantic versioning helps with upgrades. It sucks when you have to pin dependencies to certain commits to workaround like bugs https://github.com/relaxedws/couchdb-replicator/issues/10 - it's just really hard to read how old this is compared to version numbers.

Finally using tags allows composer to use dist packages. All you have to do is tag the versions, e.g. use 1.0.0 or whatever stability you prefer. For example, you can see how this works out of the box with composer & packagist with https://github.com/drunomics/drupal-project

**Comment by jeqq** [comment]
Hi @fago, thank you for reporting this. I've created a new release: 1.0.1.

**Comment by fago** [comment]
Thx, that works.
Now we just need to wait for next drupal/replication release and we have a few @dev dependencies less, thanks!
